# DO NOT EDIT! Auto-generated via carmel install.
package Carmel::MySetup;

our %environment = (
  'inc' => [
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-TagParser-0.20/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-TreeBuilder-XPath-0.14/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/arch',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tagset-3.20/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Clone-0.46/blib/arch',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Clone-0.46/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Encode-Locale-1.05/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Date-6.05/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-HTML-1.004/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/LWP-MediaTypes-6.04/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Test-Fatal-0.017/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Try-Tiny-0.31/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Tiny-0.082/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-Socket-SSL-2.081/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Mozilla-CA-20221114/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-SSLeay-1.92/blib/arch',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-SSLeay-1.92/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/JSON-4.10/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-Fetch-0.15/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Class-ErrorHandler-0.04/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/File-Listing-6.15/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Cookies-6.10/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Negotiate-6.01/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-HTTP-6.22/blib/lib',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/WWW-RobotRules-6.02/blib/lib'
  ],
  'path' => [
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/script',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/script',
    '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/script'
  ],
  'execs' => {
    'HTML::Tree' => {
      'htmltree' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/script/htmltree'
    },
    'LWP' => {
      'lwp-download' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/script/lwp-download',
      'lwp-dump' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/script/lwp-dump',
      'lwp-mirror' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/script/lwp-mirror',
      'lwp-request' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/script/lwp-request'
    },
    'Module::Build' => {
      'config_data' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/script/config_data'
    }
  },
  'base' => '/src',
  'modules' => {
    'Class/ErrorHandler.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Class-ErrorHandler-0.04/blib/lib/Class/ErrorHandler.pm',
    'Clone.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Clone-0.46/blib/lib/Clone.pm',
    'Date/Format.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Format.pm',
    'Date/Language.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language.pm',
    'Date/Language/Afar.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Afar.pm',
    'Date/Language/Amharic.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Amharic.pm',
    'Date/Language/Austrian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Austrian.pm',
    'Date/Language/Brazilian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Brazilian.pm',
    'Date/Language/Bulgarian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Bulgarian.pm',
    'Date/Language/Chinese.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Chinese.pm',
    'Date/Language/Chinese_GB.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Chinese_GB.pm',
    'Date/Language/Czech.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Czech.pm',
    'Date/Language/Danish.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Danish.pm',
    'Date/Language/Dutch.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Dutch.pm',
    'Date/Language/English.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/English.pm',
    'Date/Language/Finnish.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Finnish.pm',
    'Date/Language/French.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/French.pm',
    'Date/Language/Gedeo.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Gedeo.pm',
    'Date/Language/German.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/German.pm',
    'Date/Language/Greek.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Greek.pm',
    'Date/Language/Hungarian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Hungarian.pm',
    'Date/Language/Icelandic.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Icelandic.pm',
    'Date/Language/Italian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Italian.pm',
    'Date/Language/Norwegian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Norwegian.pm',
    'Date/Language/Occitan.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Occitan.pm',
    'Date/Language/Oromo.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Oromo.pm',
    'Date/Language/Romanian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Romanian.pm',
    'Date/Language/Russian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Russian.pm',
    'Date/Language/Russian_cp1251.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Russian_cp1251.pm',
    'Date/Language/Russian_koi8r.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Russian_koi8r.pm',
    'Date/Language/Sidama.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Sidama.pm',
    'Date/Language/Somali.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Somali.pm',
    'Date/Language/Spanish.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Spanish.pm',
    'Date/Language/Swedish.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Swedish.pm',
    'Date/Language/Tigrinya.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Tigrinya.pm',
    'Date/Language/TigrinyaEritrean.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/TigrinyaEritrean.pm',
    'Date/Language/TigrinyaEthiopian.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/TigrinyaEthiopian.pm',
    'Date/Language/Turkish.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Language/Turkish.pm',
    'Date/Parse.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Date/Parse.pm',
    'Encode/Locale.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Encode-Locale-1.05/blib/lib/Encode/Locale.pm',
    'File/Listing.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/File-Listing-6.15/blib/lib/File/Listing.pm',
    'HTML/AsSubs.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib/HTML/AsSubs.pm',
    'HTML/Element.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib/HTML/Element.pm',
    'HTML/Element/traverse.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib/HTML/Element/traverse.pm',
    'HTML/Entities.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/Entities.pm',
    'HTML/Filter.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/Filter.pm',
    'HTML/HeadParser.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/HeadParser.pm',
    'HTML/LinkExtor.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/LinkExtor.pm',
    'HTML/Parse.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib/HTML/Parse.pm',
    'HTML/Parser.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/Parser.pm',
    'HTML/PullParser.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/PullParser.pm',
    'HTML/TagParser.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-TagParser-0.20/blib/lib/HTML/TagParser.pm',
    'HTML/Tagset.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tagset-3.20/blib/lib/HTML/Tagset.pm',
    'HTML/TokeParser.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Parser-3.81/blib/lib/HTML/TokeParser.pm',
    'HTML/Tree.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib/HTML/Tree.pm',
    'HTML/TreeBuilder.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-Tree-5.07/blib/lib/HTML/TreeBuilder.pm',
    'HTML/TreeBuilder/XPath.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTML-TreeBuilder-XPath-0.14/blib/lib/HTML/TreeBuilder/XPath.pm',
    'HTTP/Config.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Config.pm',
    'HTTP/Cookies.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Cookies-6.10/blib/lib/HTTP/Cookies.pm',
    'HTTP/Cookies/Microsoft.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Cookies-6.10/blib/lib/HTTP/Cookies/Microsoft.pm',
    'HTTP/Cookies/Netscape.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Cookies-6.10/blib/lib/HTTP/Cookies/Netscape.pm',
    'HTTP/Date.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Date-6.05/blib/lib/HTTP/Date.pm',
    'HTTP/Headers.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Headers.pm',
    'HTTP/Headers/Auth.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Headers/Auth.pm',
    'HTTP/Headers/ETag.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Headers/ETag.pm',
    'HTTP/Headers/Util.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Headers/Util.pm',
    'HTTP/Message.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Message.pm',
    'HTTP/Negotiate.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Negotiate-6.01/blib/lib/HTTP/Negotiate.pm',
    'HTTP/Request.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Request.pm',
    'HTTP/Request/Common.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Request/Common.pm',
    'HTTP/Response.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Response.pm',
    'HTTP/Status.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Message-6.44/blib/lib/HTTP/Status.pm',
    'HTTP/Tiny.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/HTTP-Tiny-0.082/blib/lib/HTTP/Tiny.pm',
    'IO/HTML.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-HTML-1.004/blib/lib/IO/HTML.pm',
    'IO/Socket/SSL.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-Socket-SSL-2.081/blib/lib/IO/Socket/SSL.pm',
    'IO/Socket/SSL/Intercept.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-Socket-SSL-2.081/blib/lib/IO/Socket/SSL/Intercept.pm',
    'IO/Socket/SSL/PublicSuffix.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-Socket-SSL-2.081/blib/lib/IO/Socket/SSL/PublicSuffix.pm',
    'IO/Socket/SSL/Utils.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/IO-Socket-SSL-2.081/blib/lib/IO/Socket/SSL/Utils.pm',
    'JSON.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/JSON-4.10/blib/lib/JSON.pm',
    'JSON/backportPP.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/JSON-4.10/blib/lib/JSON/backportPP.pm',
    'JSON/backportPP/Boolean.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/JSON-4.10/blib/lib/JSON/backportPP/Boolean.pm',
    'JSON/backportPP/Compat5005.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/JSON-4.10/blib/lib/JSON/backportPP/Compat5005.pm',
    'JSON/backportPP/Compat5006.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/JSON-4.10/blib/lib/JSON/backportPP/Compat5006.pm',
    'LWP.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP.pm',
    'LWP/Authen/Basic.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Authen/Basic.pm',
    'LWP/Authen/Digest.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Authen/Digest.pm',
    'LWP/Authen/Ntlm.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Authen/Ntlm.pm',
    'LWP/ConnCache.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/ConnCache.pm',
    'LWP/Debug.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Debug.pm',
    'LWP/Debug/TraceHTTP.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Debug/TraceHTTP.pm',
    'LWP/DebugFile.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/DebugFile.pm',
    'LWP/MediaTypes.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/LWP-MediaTypes-6.04/blib/lib/LWP/MediaTypes.pm',
    'LWP/MemberMixin.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/MemberMixin.pm',
    'LWP/Protocol.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol.pm',
    'LWP/Protocol/cpan.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/cpan.pm',
    'LWP/Protocol/data.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/data.pm',
    'LWP/Protocol/file.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/file.pm',
    'LWP/Protocol/ftp.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/ftp.pm',
    'LWP/Protocol/gopher.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/gopher.pm',
    'LWP/Protocol/http.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/http.pm',
    'LWP/Protocol/loopback.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/loopback.pm',
    'LWP/Protocol/mailto.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/mailto.pm',
    'LWP/Protocol/nntp.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/nntp.pm',
    'LWP/Protocol/nogo.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Protocol/nogo.pm',
    'LWP/RobotUA.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/RobotUA.pm',
    'LWP/Simple.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/Simple.pm',
    'LWP/UserAgent.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/libwww-perl-6.68/blib/lib/LWP/UserAgent.pm',
    'Module/Build.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build.pm',
    'Module/Build/Base.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Base.pm',
    'Module/Build/Compat.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Compat.pm',
    'Module/Build/Config.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Config.pm',
    'Module/Build/ConfigData.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/ConfigData.pm',
    'Module/Build/Cookbook.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Cookbook.pm',
    'Module/Build/Dumper.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Dumper.pm',
    'Module/Build/Notes.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Notes.pm',
    'Module/Build/PPMMaker.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/PPMMaker.pm',
    'Module/Build/Platform/Default.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/Default.pm',
    'Module/Build/Platform/MacOS.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/MacOS.pm',
    'Module/Build/Platform/Unix.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/Unix.pm',
    'Module/Build/Platform/VMS.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/VMS.pm',
    'Module/Build/Platform/VOS.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/VOS.pm',
    'Module/Build/Platform/Windows.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/Windows.pm',
    'Module/Build/Platform/aix.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/aix.pm',
    'Module/Build/Platform/cygwin.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/cygwin.pm',
    'Module/Build/Platform/darwin.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/darwin.pm',
    'Module/Build/Platform/os2.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/Platform/os2.pm',
    'Module/Build/PodParser.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Module-Build-0.4232/blib/lib/Module/Build/PodParser.pm',
    'Mozilla/CA.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Mozilla-CA-20221114/blib/lib/Mozilla/CA.pm',
    'Net/HTTP.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-HTTP-6.22/blib/lib/Net/HTTP.pm',
    'Net/HTTP/Methods.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-HTTP-6.22/blib/lib/Net/HTTP/Methods.pm',
    'Net/HTTP/NB.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-HTTP-6.22/blib/lib/Net/HTTP/NB.pm',
    'Net/HTTPS.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-HTTP-6.22/blib/lib/Net/HTTPS.pm',
    'Net/SSLeay.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-SSLeay-1.92/blib/lib/Net/SSLeay.pm',
    'Net/SSLeay/Handle.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Net-SSLeay-1.92/blib/lib/Net/SSLeay/Handle.pm',
    'Test/Fatal.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Test-Fatal-0.017/blib/lib/Test/Fatal.pm',
    'Time/Zone.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/Time/Zone.pm',
    'TimeDate.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/TimeDate-2.33/blib/lib/TimeDate.pm',
    'Try/Tiny.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/Try-Tiny-0.31/blib/lib/Try/Tiny.pm',
    'URI.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI.pm',
    'URI/Escape.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/Escape.pm',
    'URI/Fetch.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-Fetch-0.15/blib/lib/URI/Fetch.pm',
    'URI/Fetch/Response.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-Fetch-0.15/blib/lib/URI/Fetch/Response.pm',
    'URI/Heuristic.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/Heuristic.pm',
    'URI/IRI.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/IRI.pm',
    'URI/QueryParam.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/QueryParam.pm',
    'URI/Split.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/Split.pm',
    'URI/URL.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/URL.pm',
    'URI/WithBase.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/WithBase.pm',
    'URI/_foreign.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_foreign.pm',
    'URI/_generic.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_generic.pm',
    'URI/_idna.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_idna.pm',
    'URI/_ldap.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_ldap.pm',
    'URI/_login.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_login.pm',
    'URI/_punycode.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_punycode.pm',
    'URI/_query.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_query.pm',
    'URI/_segment.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_segment.pm',
    'URI/_server.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_server.pm',
    'URI/_userpass.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/_userpass.pm',
    'URI/data.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/data.pm',
    'URI/file.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file.pm',
    'URI/file/Base.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/Base.pm',
    'URI/file/FAT.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/FAT.pm',
    'URI/file/Mac.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/Mac.pm',
    'URI/file/OS2.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/OS2.pm',
    'URI/file/QNX.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/QNX.pm',
    'URI/file/Unix.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/Unix.pm',
    'URI/file/Win32.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/file/Win32.pm',
    'URI/ftp.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/ftp.pm',
    'URI/gopher.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/gopher.pm',
    'URI/http.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/http.pm',
    'URI/https.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/https.pm',
    'URI/ldap.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/ldap.pm',
    'URI/ldapi.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/ldapi.pm',
    'URI/ldaps.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/ldaps.pm',
    'URI/mailto.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/mailto.pm',
    'URI/mms.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/mms.pm',
    'URI/news.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/news.pm',
    'URI/nntp.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/nntp.pm',
    'URI/nntps.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/nntps.pm',
    'URI/pop.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/pop.pm',
    'URI/rlogin.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/rlogin.pm',
    'URI/rsync.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/rsync.pm',
    'URI/rtsp.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/rtsp.pm',
    'URI/rtspu.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/rtspu.pm',
    'URI/sftp.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/sftp.pm',
    'URI/sip.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/sip.pm',
    'URI/sips.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/sips.pm',
    'URI/snews.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/snews.pm',
    'URI/ssh.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/ssh.pm',
    'URI/telnet.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/telnet.pm',
    'URI/tn3270.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/tn3270.pm',
    'URI/urn.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/urn.pm',
    'URI/urn/isbn.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/urn/isbn.pm',
    'URI/urn/oid.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/URI-5.17/blib/lib/URI/urn/oid.pm',
    'WWW/RobotRules.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/WWW-RobotRules-6.02/blib/lib/WWW/RobotRules.pm',
    'WWW/RobotRules/AnyDBM_File.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/WWW-RobotRules-6.02/blib/lib/WWW/RobotRules/AnyDBM_File.pm',
    'XML/XPathEngine.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine.pm',
    'XML/XPathEngine/Boolean.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Boolean.pm',
    'XML/XPathEngine/Expr.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Expr.pm',
    'XML/XPathEngine/Function.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Function.pm',
    'XML/XPathEngine/Literal.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Literal.pm',
    'XML/XPathEngine/LocationPath.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/LocationPath.pm',
    'XML/XPathEngine/NodeSet.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/NodeSet.pm',
    'XML/XPathEngine/Number.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Number.pm',
    'XML/XPathEngine/Root.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Root.pm',
    'XML/XPathEngine/Step.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Step.pm',
    'XML/XPathEngine/Variable.pm' => '/root/.carmel/5.36.0-x86_64-linux-gnu/builds/XML-XPathEngine-0.14/blib/lib/XML/XPathEngine/Variable.pm'
  },
  'prereqs' => {
    'runtime' => {
      'requires' => {
        'HTML::TagParser' => '0',
        'HTML::TreeBuilder::XPath' => '0',
        'HTTP::Tiny' => '0',
        'IO::Socket::SSL' => '0',
        'JSON' => '0',
        'Net::SSLeay' => '0',
        'URI' => '0',
        'URI::Fetch' => '0'
      }
    }
  },
);

1;
